### ISSUE TITLE
getChainById()

### ISSUE THREAD

**Issue by wkande** [api3dao/chains#13]
Getting a chain by its ID would be nice. When I get the [references.json](https://github.com/api3dao/airnode/blob/master/packages/airnode-protocol/deployments/references.json) file from `airnode-protocol` there isn't a `short-name` for me to use. The closet thing is the `network` or `chains` obj but these may not be reliable and since @api3/chains is the single source of truth I'd rather not rely on them.

For now I must use my own function that spins through the array in CHAINS.

**Comment by andreogle** [comment]
I'm not sure how I feel about adding more of these kinds of utility functions. `getChainByAlias` was mostly just kept around because it was existing v1.x behaviour. It's a one liner in the importing module and this is basically what would be implemented here anyway.

```ts
const chain = CHAINS.find((chain) => chain.id === id);
```

Then just a few more lines to check that it exists, or just let it throw by trying to use `undefined` later (current `getChainByAlias()` behaviour).

```ts
if (!chain) {
  // handle bad name
}
```

**Comment by bbenligiray** [comment]
To me even `getChainByAlias()` is a bit extra

**Comment by wkande** [comment]
OK, it is pretty easy for me to check. Closing my request as not needed.
