### ISSUE TITLE
Override `changeset` requirements

### ISSUE THREAD

**Issue by hiletmis** [api3dao/chains#272]
**The issue**
* CI requires changeset on any PR including `renovate`

Maybe this should be overridden via a label or something. Every push or PR may not meant to trigger a patch.

WDYT?

@dcroote @andreogle

**Comment by andreogle** [comment]
I think CI should _probably_ not require a changeset (?) It can occasionally be useful if there are dependencies that cause breaking changes though I guess.

And maybe for other PRs that don't require a version bump, we can just require an empty changeset? I kinda like that it's opt-out, rather than opt-in, so we don't forget

**Comment by dcroote** [comment]
I think this could be solved in two parts and still keep the changeset requirement (it can be easy to forget otherwise):
1. Bypass changesets for renovate using the [same approach as Airnode](https://github.com/api3dao/airnode/blob/0bb350f165899c38abdc3c87f034df3134f02c52/.github/workflows/build-test.yml#L184)
2. Ourselves run `pnpm changeset --empty` and commit the resulting empty file when we don't need to trigger a patch

**Comment by hiletmis** [comment]
I have opened a [PR](https://github.com/api3dao/chains/pull/280) to demonstrate the solution @dcroote suggested.
