### ISSUE TITLE
Revise names

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/chains#63]
Some chain names don't match what its core team prefers, e.g. Arbitrum vs. Arbitrum One, BSC vs BNB chain, etc. They should be revised.

**Comment by andreogle** [comment]
Is there someone on the team who we can assign this to? Otherwise I can try a best effort Google for each one

**Comment by BTT21000** [comment]
Happy to help doing the research, feel free to assign me to the task.

**Comment by dcroote** [comment]
Relevant thread: https://api3workspace.slack.com/archives/C02R79STBRA/p1691789296814869

**Comment by BTT21000** [comment]
Hi @andreogle,

See the research draft results for the chains revised names:
https://docs.google.com/spreadsheets/d/1rYZ3fVhyNkfNqEnDxvGxyqQpCmPajrm9FLHOMXt9vbM/edit?usp=sharing

Feel free to review and comment. And let me know if you need them on another format (e.g. json) to update the repo.
Aslo see below some notes/questions.

**Notes/Questions**:
- Results were typically extracted from https://chainlist.org/ and checked against the respective sites of each projects.
- The avalanche mainnet appears to be more commonly referred to as [Avalanche C-Chain](https://support.avax.network/en/articles/4626956-how-to-connect-metamask-to-avalanche), would you then prefer to replace `avalanche` with `avalanche-c-chain`
- Regarding the `base-goerli-testnet` (chainid=84531). Note that the [docs](https://docs.base.org/using-base/) also show the Base Sepolia Testnet (chainId = 84532) so you may decide to add `base-sepolia-testnet` as well at some stage.
- The [godwoken](https://docs.godwoken.io/connectionInfo) public network appears to have a Godwoken Mainnet v1 and Godwoken Mainnet v0 networks. Please advise if you'd like to specify the network version and have`godwoken-mainnet-v1` or `godwoken-v1` instead of `godwoken` (chainId = 71402).
- Note that milkomeda also appear to have a [milkomeda-a1](https://medium.com/@milkomedafoundation/the-milkomeda-a1-rollup-is-now-live-on-algorand-mainnet-95bdb0a9d13e) network (Algorand). We may want to discuss and consider this one if it is relevant for our users.
- It appears that the `scroll-goerli-testnet` we have (chainid=534353) should be called [`scroll-alpha-testnet`](https://chainlist.org/chain/534353). Also the official docs now seem to refer to [scroll sepolia](https://sepolia.scroll.io/portal) (chainId = 534351). Are we using a superseded scroll testnet and should we add/use `scroll-sepolia-testnet` too/instead?

**Comment by BTT21000** [comment]
FYI following today's meeting, this issue has been created https://github.com/api3dao/tasks/issues/312:

> Testnet chains with goerli in their name should be replaced by sepolia testnets once it is verified that sepolia exists for these testnet chains and add them to the live list of [newChainsToAdd.md](https://github.com/api3dao/tasks/blob/main/Chain%20Integrations/newChainsToAdd.md).

**Comment by andreogle** [comment]
This list looks great, thanks for being so thorough. I'm not really sure the best way to go from here. See @bbenligiray 's [comment](https://github.com/api3dao/chains/pull/85#discussion_r1364060185) for some more thoughts. I previously changed Avalanche Fuji and Gnosis Chiado but ended up reverting that.

I guess to try to summarise my thoughts:

| Old name | New name | Should be updated? |
| --------- | ---------- | -------------- |
| Arbitrum | Arbitrum One | ✅ |
| Avalanche Testnet | Avalanche Fuji Testnet | ❌ |
| BSC Testnet | BNB Smart Chain Testnet | ✅  |
| BSC | BNB Smart Chain | ✅ |
| Fantom | Fantom Opera | ❌ - probably |
| Gnosis Testnet | Gnosis Chiado Testnet | ❌ |
| Gnosis | Gnosis Chain | ❌ |
| Mantle Goerli Testnet | Mantle Testnet | ❌ |
| Metis | Metis Andromeda | ❓ |
| Moonbeam Testnet | Moonbase Alpha Testnet | ❌ |
| Polygon Testnet | Polygon Mumbai Testnet | ❌ |
| Polygon zkEVM Goerli Testnet | Polygon zkEVM Testnet | ❌ |
| Scroll Goerli Testnet | Scroll Alpha Testnet | ❓ - maybe just "Scroll Testnet"? |
| SX Testnet | SX Toronto Testnet | ❌ |
| zkSync Goerli Testnet | zkSync Era Testnet | ❌ |
| zkSync | zkSync Era | ❌ |

I guess to come back to the purpose of this repo - it's (to my understanding) an indication of the chains that API3 as a whole currently supports, mainly through the market. This means that as new versions of this repo get released, some chains will have their underlying data changed. e.g. a testnet changing from Goerli to Sepolia. This means to me that it _should_ be fine to keep the names simple and try to follow a pattern of "[chain]" for mainnet and "[chain] Testnet" for testnet. But, I'm not an end user of this repo currently so don't necessarily feel qualified enough to make the final decision here.

To answer some of your questions:

1. I'm not sure about Godwoken. I _assume_ based on the naming that we probably want the "v1" version (?)
2. Unsure about Milkomeda A1
3. Unsure about Scroll
4. Unsure about Cronos (sorry lots of unsures 😅)

**Comment by BTT21000** [comment]
@andreogle thanks for the feedback, the simplistic pattern to:
> follow a pattern of "[chain]" for mainnet and "[chain] Testnet"

is a good approach. We'll just have to be careful to not confuse users between goerli or sepolia testnets as we transition from goerli to sepolia as per this [issue](https://github.com/api3dao/tasks/issues/312).

**Comment by andreogle** [comment]
Thanks @BTT21000 I've opened a PR for this now - happy to adjust anything else if necessary. I'll release v4.0.0 when this PR is merged.

> We'll just have to be careful to not confuse users between goerli or sepolia testnets as we transition from goerli to sepolia as per this https://github.com/api3dao/tasks/issues/312.

Most of our chains currently have the specific testnet name in the name/alias, but some don't (e.g. `avalanche`, `gnosis-testnet` and `polygon-testnet`). I think specifically for Goerli -> Sepolia though, we should be ok

**Comment by BTT21000** [comment]
Thanks @andreogle, FYI some additional info in this [issue](https://github.com/api3dao/tasks/issues/312)/[comment](https://github.com/api3dao/tasks/issues/312#issuecomment-1792065162) and findings regarding the transition from goerli to sepolia as well as some considerations about testnets integrations in general.
